@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "VueDifferentTableau" as VDT
participant "ControleurTableauClicDroit" as CTC
participant "Modele" as M
participant "Tableau" as T


User -> VDT: clic droit
VDT -> CTC: clic droit
CTC -> CTC: afficher menu contextuel
alt chanchement de Titre
    CTC -> M: getTableau().get(NumTab).changerTitre(Titre)
    M -> T: changerTitre()
    T --> CTC: titre changé
    CTC --> VDT: titre changé
end
@enduml